# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_searchparcels2.ui'
#
# Created: Wed Jun 18 13:45:00 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SearchParcels2(object):
    def setupUi(self, SearchParcels2):
        SearchParcels2.setObjectName(_fromUtf8("SearchParcels2"))
        SearchParcels2.resize(516, 383)
        self.gridLayout = QtGui.QGridLayout(SearchParcels2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(SearchParcels2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layerWidgetGroup = QtGui.QWidget(self.frame)
        self.layerWidgetGroup.setObjectName(_fromUtf8("layerWidgetGroup"))
        self.formLayout = QtGui.QFormLayout(self.layerWidgetGroup)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.uptadeButton = QtGui.QPushButton(self.layerWidgetGroup)
        self.uptadeButton.setObjectName(_fromUtf8("uptadeButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.uptadeButton)
        self.comboBox = QtGui.QComboBox(self.layerWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label = QtGui.QLabel(self.layerWidgetGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.gridLayout_2.addWidget(self.layerWidgetGroup, 1, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.frame)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.progressBar = QtGui.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 0, 0, 1, 1)
        self.cancelButton = QtGui.QPushButton(self.widget_2)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout_3.addWidget(self.cancelButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 6, 0, 1, 1)
        self.CheckWidgetGroup = QtGui.QWidget(self.frame)
        self.CheckWidgetGroup.setObjectName(_fromUtf8("CheckWidgetGroup"))
        self.gridLayout_5 = QtGui.QGridLayout(self.CheckWidgetGroup)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.goButton = QtGui.QPushButton(self.CheckWidgetGroup)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.gridLayout_5.addWidget(self.goButton, 0, 2, 1, 1)
        self.widget_3 = QtGui.QWidget(self.CheckWidgetGroup)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.selectBox = QtGui.QCheckBox(self.widget_3)
        self.selectBox.setChecked(True)
        self.selectBox.setObjectName(_fromUtf8("selectBox"))
        self.gridLayout_4.addWidget(self.selectBox, 0, 0, 1, 1)
        self.panBox = QtGui.QCheckBox(self.widget_3)
        self.panBox.setChecked(True)
        self.panBox.setObjectName(_fromUtf8("panBox"))
        self.gridLayout_4.addWidget(self.panBox, 0, 1, 1, 1)
        self.scaleBox = QtGui.QCheckBox(self.widget_3)
        self.scaleBox.setObjectName(_fromUtf8("scaleBox"))
        self.gridLayout_4.addWidget(self.scaleBox, 1, 0, 1, 1)
        self.formBox = QtGui.QCheckBox(self.widget_3)
        self.formBox.setObjectName(_fromUtf8("formBox"))
        self.gridLayout_4.addWidget(self.formBox, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.CheckWidgetGroup, 5, 0, 1, 1)
        self.SearchWidgetGroup = QtGui.QWidget(self.frame)
        self.SearchWidgetGroup.setObjectName(_fromUtf8("SearchWidgetGroup"))
        self.formLayout_2 = QtGui.QFormLayout(self.SearchWidgetGroup)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.ParticelLine = QtGui.QLineEdit(self.SearchWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParticelLine.sizePolicy().hasHeightForWidth())
        self.ParticelLine.setSizePolicy(sizePolicy)
        self.ParticelLine.setObjectName(_fromUtf8("ParticelLine"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ParticelLine)
        self.campo1 = QtGui.QComboBox(self.SearchWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.campo1.sizePolicy().hasHeightForWidth())
        self.campo1.setSizePolicy(sizePolicy)
        self.campo1.setObjectName(_fromUtf8("campo1"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.campo1)
        self.campo2 = QtGui.QComboBox(self.SearchWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.campo2.sizePolicy().hasHeightForWidth())
        self.campo2.setSizePolicy(sizePolicy)
        self.campo2.setObjectName(_fromUtf8("campo2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.campo2)
        self.FoglioLine = QtGui.QLineEdit(self.SearchWidgetGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FoglioLine.sizePolicy().hasHeightForWidth())
        self.FoglioLine.setSizePolicy(sizePolicy)
        self.FoglioLine.setObjectName(_fromUtf8("FoglioLine"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.FoglioLine)
        self.gridLayout_2.addWidget(self.SearchWidgetGroup, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(SearchParcels2)
        QtCore.QMetaObject.connectSlotsByName(SearchParcels2)

    def retranslateUi(self, SearchParcels2):
        SearchParcels2.setWindowTitle(_translate("SearchParcels2", "SearchParcels2", None))
        self.uptadeButton.setText(_translate("SearchParcels2", "Aggiorna Layer", None))
        self.label.setText(_translate("SearchParcels2", "Layer", None))
        self.cancelButton.setText(_translate("SearchParcels2", "Cancella", None))
        self.goButton.setText(_translate("SearchParcels2", "Cerca", None))
        self.selectBox.setText(_translate("SearchParcels2", "seleziona", None))
        self.panBox.setText(_translate("SearchParcels2", "centra", None))
        self.scaleBox.setText(_translate("SearchParcels2", "zoom", None))
        self.formBox.setText(_translate("SearchParcels2", "info elemento", None))

